### ISSUE TITLE
TO_FILE is deprecated, use CODECLIMATE_TO_FILE

### ISSUE THREAD

**Issue by mhutter** [grosser/codeclimate_batch#2]
From Test Output on Travis-CI:

```
Coverage = 94.07%. TO_FILE is deprecated, use CODECLIMATE_TO_FILE
```

(https://travis-ci.org/mhutter/wikimd/jobs/82447376, Line 219)

**Comment by grosser** [comment]
FYI you can speedup that build from 2 min -> 1 min by using

```
script: bundle exec rake $TASK
env:
  - TASK: rspec
  - TASK: cucumber
after_script:
  - codeclimate-batch --groups 4
```
